# Generated by Django 6.0.2 on 2026-02-22 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('activity_count', 'Activity Count'), ('distance_total', 'Total Distance'), ('calories_total', 'Total Calories'), ('streak', 'Activity Streak')], max_length=30)),
                ('value', models.IntegerField()),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
                'unique_together': {('user', 'milestone_type', 'value')},
            },
        ),
    ]
