### Get Token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "maryqueen",
  "password": "mary1234"
}

### Access Token & IDs
@FitAdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMzg1NTIwLCJpYXQiOjE3NzIzODE5MjAsImp0aSI6ImU3MzgwYTU4NGQyODQxNTI4ZTc4NGRjYzA1NjM4Y2U1IiwidXNlcl9pZCI6IjEifQ.srkcuhXieybycL4pQ4hr-9KBEsjFjunM5ZkYjYznhVo
@mikeToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMzg1NTcxLCJpYXQiOjE3NzIzODE5NzEsImp0aSI6ImEzNTJlYjBhNDFhNzQ0ZGI4YTBjMTQ5YmRmYjRkMGMwIiwidXNlcl9pZCI6IjMifQ.MVYFZndqEBofmWswVrXhUMULhX9yGjmrHkRi15FH5JY
@maryToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMzg1OTgwLCJpYXQiOjE3NzIzODIzODAsImp0aSI6ImI1OTBlNjdjZTdjODRiMTI5NTM5NDFmYmZmYTdlZjJkIiwidXNlcl9pZCI6IjQifQ.1GTLM8Vep-vge6CQ7M47PTxYUK4GyI2idq5wUmAUygs
@martinsToken = 
@activityId = 15
@postID = 6
@postID2 = 

### Refresh Token
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTg0MDIxMCwiaWF0IjoxNzcxNzUzODEwLCJqdGkiOiJjM2U0MzY1MTE2MTU0ZTI5OWYzODQ3YzQ4MThhOTA5NyIsInVzZXJfaWQiOiIxIn0.VaXcr-Ls3_7D1pikj2AxXtJ00_vxPqAp0feGddBpLr0
}

### Create Activity
POST http://127.0.0.1:8000/api/activities/
Authorization: Bearer {{FitAdminToken}}
Content-Type: application/json

{
  "activity_type": "run",
  "duration_minutes": 60,
  "distance_km": 100,
  "calories_burned": 100,
  "activity_date": "2026-03-01",
  "notes": "First run of the March month."
}

### Get Activity List
GET http://127.0.0.1:8000/api/activities/
Authorization: Bearer {{FitAdminToken}}
Content-Type: application/json


### Share Community Posts
POST http://127.0.0.1:8000/api/community/posts/
Authorization: Bearer {{FitAdminToken}}
Content-Type: application/json

{
  "activity": {{activityId}},
  "content": "I completed my first run in march!"
}

### Users Comment on a Post
POST http://127.0.0.1:8000/api/community/posts/{{postID}}/comment/
Authorization: Bearer {{maryToken}}
Content-Type: application/json

{
  "content": "Hurray to you!"
}

### Users likes a post.
POST http://127.0.0.1:8000/api/community/posts/{{postID}}/like/
Authorization: Bearer {{mikeToken}}


### View Community Posts
GET http://127.0.0.1:8000/api/community/posts/
Authorization: Bearer {{FitAdminToken}}
Content-Type: application/json

### Users Workout Insights
GET http://127.0.0.1:8000/api/ai/workout-insights/
Authorization: Bearer {{FitAdminToken}}


## Users Analytics ##
### Get Activity Duration & Analytics
GET http://127.0.0.1:8000/api/activities/analytics/
Authorization: Bearer {{FitAdminToken}}

### Get Activity by Date Range
GET http://127.0.0.1:8000/api/activities/analytics/?start_date=2026-02-25&end_date=2026-02-28
Authorization: Bearer {{FitAdminToken}}
