### Get Token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "martins",
  "password": "mary1234"
}

### Access Token
@FitAdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjU1NjE4LCJpYXQiOjE3NzIyNTIwMTksImp0aSI6IjY1NzA4MmM2OWU5MzQ5MGM4NTc4NTVjNTUzMjExOWE4IiwidXNlcl9pZCI6IjEifQ.r3s9Eh_kQYnmZtT9msbGPa1rCoQsIj2zYOO4HxKyB9o
@mikeToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjU1NzUwLCJpYXQiOjE3NzIyNTIxNTAsImp0aSI6ImUxMWE2NmE4NDQyZDQ2MTNiNDMxNzdlYTA2YjMxNDc3IiwidXNlcl9pZCI6IjMifQ.VwNIkI_DN8lHMDuOXOjd_r69pm35wwZjBTwVP1L_xGk
@maryToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjU1ODM4LCJpYXQiOjE3NzIyNTIyMzgsImp0aSI6ImNhNjhlNjliODI0MTRiNjI5NzM2NGNiYTFkNDBmY2FiIiwidXNlcl9pZCI6IjQifQ.8CQipz0Crv4SRCLyF5iqLYRrL1xoUwQMfuwHj4qHPqg
@martinsToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjU1ODc3LCJpYXQiOjE3NzIyNTIyNzcsImp0aSI6IjFkNTU2NmFiMTVlMzQwYmNhYzRjODM2NWE1YjUyNGM0IiwidXNlcl9pZCI6IjUifQ.m9Ss4_Y_gc_cxisTQYFAAF-bxvDUJkvMgUCUqoDfOFk
@activityId = 11
@postID = 3
@postID2 = 2

### Refresh Token
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTg0MDIxMCwiaWF0IjoxNzcxNzUzODEwLCJqdGkiOiJjM2U0MzY1MTE2MTU0ZTI5OWYzODQ3YzQ4MThhOTA5NyIsInVzZXJfaWQiOiIxIn0.VaXcr-Ls3_7D1pikj2AxXtJ00_vxPqAp0feGddBpLr0
}

### Create Activity
POST http://127.0.0.1:8000/api/activities/
Authorization: Bearer {{mikeToken}}
Content-Type: application/json

{
  "activity_type": "run",
  "duration_minutes": 60,
  "distance_km": 120,
  "calories_burned": 200,
  "activity_date": "2026-02-26",
  "notes": "improving my endurance."
}

### Get Activity List
GET http://127.0.0.1:8000/api/activities/
Authorization: Bearer {{FitAdminToken}}
Content-Type: application/json


### Share Community Posts
POST http://127.0.0.1:8000/api/community/posts/
Authorization: Bearer {{FitAdminToken}}
Content-Type: application/json

{
  "activity": {{activityId}},
  "content": "I completed my first yoga for the week!"
}

### Users Comment on a Post
POST http://127.0.0.1:8000/api/community/posts/{{postID}}/comment/
Authorization: Bearer {{mikeToken}}
Content-Type: application/json

{
  "content": "Congratulations to you!"
}

### Users likes a post.
POST http://127.0.0.1:8000/api/community/posts/{{postID}}/like/
Authorization: Bearer {{maryToken}}


### View Community Posts
GET http://127.0.0.1:8000/api/community/posts/
Authorization: Bearer {{martinsToken}}
Content-Type: application/json

### Users Workout Insights
GET http://127.0.0.1:8000/api/ai/workout-insights/
Authorization: Bearer {{FitAdminToken}}


## Users Analytics ##
### Get Activity Duration & Analytics
GET http://127.0.0.1:8000/api/activities/analytics/
Authorization: Bearer {{FitAdminToken}}

### Get Activity by Date Range
GET http://127.0.0.1:8000/api/activities/analytics/?start_date=2026-02-20&end_date=2026-02-26
Authorization: Bearer {{FitAdminToken}}
