### Get Token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "FitAdmin",
  "password": "FitAdmin2026"
}

### Refresh Token
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTg0MDIxMCwiaWF0IjoxNzcxNzUzODEwLCJqdGkiOiJjM2U0MzY1MTE2MTU0ZTI5OWYzODQ3YzQ4MThhOTA5NyIsInVzZXJfaWQiOiIxIn0.VaXcr-Ls3_7D1pikj2AxXtJ00_vxPqAp0feGddBpLr0
}


### Get Activity List
GET http://127.0.0.1:8000/api/activities/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjA5OTEzLCJpYXQiOjE3NzIyMDYzMTMsImp0aSI6ImQxZmQ5NGE0ZmYxMjQ4N2Y5MDIyMTY5NjlkYjU5ODU2IiwidXNlcl9pZCI6IjEifQ.u2z3RsARA6noowYf2bruOMkeadAEVtOH0LZKmlqIlSs
Content-Type: application/json


### Create Activity
POST http://127.0.0.1:8000/api/activities/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjA5OTEzLCJpYXQiOjE3NzIyMDYzMTMsImp0aSI6ImQxZmQ5NGE0ZmYxMjQ4N2Y5MDIyMTY5NjlkYjU5ODU2IiwidXNlcl9pZCI6IjEifQ.u2z3RsARA6noowYf2bruOMkeadAEVtOH0LZKmlqIlSs
Content-Type: application/json

{
  "activity_type": "run",
  "duration_minutes": 100,
  "distance_km": 150,
  "calories_burned": 200,
  "activity_date": "2026-02-24"
}

### Get Activity Duration & Analytics
GET http://127.0.0.1:8000/api/activities/analytics/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjA5OTEzLCJpYXQiOjE3NzIyMDYzMTMsImp0aSI6ImQxZmQ5NGE0ZmYxMjQ4N2Y5MDIyMTY5NjlkYjU5ODU2IiwidXNlcl9pZCI6IjEifQ.u2z3RsARA6noowYf2bruOMkeadAEVtOH0LZKmlqIlSs

### Get Activity by Date Range
GET http://127.0.0.1:8000/api/activities/analytics/?start_date=2026-02-20&end_date=2026-02-27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjA5OTEzLCJpYXQiOjE3NzIyMDYzMTMsImp0aSI6ImQxZmQ5NGE0ZmYxMjQ4N2Y5MDIyMTY5NjlkYjU5ODU2IiwidXNlcl9pZCI6IjEifQ.u2z3RsARA6noowYf2bruOMkeadAEVtOH0LZKmlqIlSs

### Make Community Posts
POST http://127.0.0.1:8000/api/community/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjA5OTEzLCJpYXQiOjE3NzIyMDYzMTMsImp0aSI6ImQxZmQ5NGE0ZmYxMjQ4N2Y5MDIyMTY5NjlkYjU5ODU2IiwidXNlcl9pZCI6IjEifQ.u2z3RsARA6noowYf2bruOMkeadAEVtOH0LZKmlqIlSs
Content-Type: application/json

{
  "content": "I Just completed a 6 day streak!"
}

### Comment on a Post
POST http://127.0.0.1:8000/api/community/posts/1/comment/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjA5OTEzLCJpYXQiOjE3NzIyMDYzMTMsImp0aSI6ImQxZmQ5NGE0ZmYxMjQ4N2Y5MDIyMTY5NjlkYjU5ODU2IiwidXNlcl9pZCI6IjEifQ.u2z3RsARA6noowYf2bruOMkeadAEVtOH0LZKmlqIlSs
Content-Type: application/json

{
  "content": "What an amazing work!"
}

### Get Community Posts
GET http://127.0.0.1:8000/api/community/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjA5OTEzLCJpYXQiOjE3NzIyMDYzMTMsImp0aSI6ImQxZmQ5NGE0ZmYxMjQ4N2Y5MDIyMTY5NjlkYjU5ODU2IiwidXNlcl9pZCI6IjEifQ.u2z3RsARA6noowYf2bruOMkeadAEVtOH0LZKmlqIlSs
Content-Type: application/json

### Users Workout Insights
GET http://127.0.0.1:8000/api/ai/workout-insights/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjA5OTEzLCJpYXQiOjE3NzIyMDYzMTMsImp0aSI6ImQxZmQ5NGE0ZmYxMjQ4N2Y5MDIyMTY5NjlkYjU5ODU2IiwidXNlcl9pZCI6IjEifQ.u2z3RsARA6noowYf2bruOMkeadAEVtOH0LZKmlqIlSs